Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "most2",
          :ip => "172.18.1.14",
          :name => 'most2'
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "ubuntu/jammy64"
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
			node.vm.network "forwarded_port", guest: 80, host: 82
			node.vm.network "forwarded_port", guest: 10050, host: 10051
			node.vm.network "forwarded_port", guest: 80, host: 8081
			node.vm.network "forwarded_port", guest: 8080, host: 81
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 2048, "--cpus", 2]
                vb.name = machine[:name]
            end
                end
    end
end
