name: CI Pipeline
on: [push]  # Запуск при push

jobs:
  build:
    runs-on: ubuntu-latest  # Используется удалённый сервер с Ubuntu
    steps:
      - uses: actions/checkout@v4  # Копирует ваш код на сервер CI
      - name: Run Hello World
        run:  hello.sh  # Запуск скрипта на удалённом сервере
